# Generated by Django 2.2.7 on 2019-12-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, help_text='Latitude', null=True)),
                ('lon', models.FloatField(blank=True, help_text='Longitude', null=True)),
                ('squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', max_length=16)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=16, null=True)),
                ('pri_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=16, null=True)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=30, null=True)),
                ('specific_location', models.CharField(blank=True, help_text='specific location of squirrel', max_length=200, null=True)),
                ('running', models.BooleanField(blank=True, null=True)),
                ('chasing', models.BooleanField(blank=True, null=True)),
                ('climbing', models.BooleanField(blank=True, null=True)),
                ('eating', models.BooleanField(blank=True, null=True)),
                ('foraging', models.BooleanField(blank=True, null=True)),
                ('other_activities', models.CharField(blank=True, max_length=200, null=True)),
                ('kuks', models.BooleanField(blank=True, null=True)),
                ('quaas', models.BooleanField(blank=True, null=True)),
                ('moans', models.BooleanField(blank=True, null=True)),
                ('tail_flags', models.BooleanField(blank=True, null=True)),
                ('tail_twitches', models.BooleanField(blank=True, null=True)),
                ('approaches', models.BooleanField(blank=True, null=True)),
                ('indifferent', models.BooleanField(blank=True, null=True)),
                ('runs_from', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
